version: "3.8"

services:
  ansible:
    build: .
    image: sezar/ansible:v1
    container_name: ansible
    hostname: ansible
    volumes:
      -  ../playbooks:/hero/playbooks
      - ./entry:/hero/entry
      - ../playbooks/:/etc/ansible/
    depends_on:
      - serv04
      - serv02
      - serv03
    networks:
      ansible:
        ipv4_address: 10.5.0.5
    # entrypoint: /hero/entry/ansible.sh
  
  serv04:
    build: ./dockerfile-serv
    image: sezar/linux-serv:v1
    container_name: serv04
    hostname: serv04
    ports:
      - "9501:22"
    volumes:
      - ./entry:/hero/entry
    networks:
      ansible:
        ipv4_address: 10.5.0.4
    # entrypoint: /hero/entry/serv.sh
    
  
  serv02:
    build: ./dockerfile-serv
    image: sezar/linux-serv:v1
    container_name: serv02
    hostname: serv02
    ports:
      - "9502:22"
    volumes:
      - ./entry:/hero/entry
    networks:
      ansible:
        ipv4_address: 10.5.0.2
    # entrypoint: /hero/entry/serv.sh

  
  serv03:
    build: ./dockerfile-serv
    image: sezar/linux-serv:v1
    container_name: serv03
    hostname: serv03
    ports:
      - "9503:22"
    volumes:
      - ./entry:/hero/entry
    networks:
      ansible:
        ipv4_address: 10.5.0.3
    # entrypoint: /hero/entry/serv.sh

networks:
  ansible:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1