FROM sickp/centos-sshd


# Labels.
LABEL maintainer="mahmoud@sezar.sy" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.name="sezar/ansible" \
    org.label-schema.description="Ansible inside Docker" \
    org.label-schema.url="https://github.com/sezarMbar/docker-ansible" \
    org.label-schema.vcs-url="https://github.com/sezarMbar/docker-ansible" \
    org.label-schema.vendor="Mahmoud Barakat Online" \
    org.label-schema.docker.cmd="docker run --rm -it -v $(pwd):/ansible -v ~/.ssh/id_rsa:/root/id_rsa sezar/ansible:2.11-ubuntu-18.04"

