---
- hosts: all
  become: true
  pre_tasks:
    - name: install update (CentOS)
      dnf:
        update_only: yes
        # update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        # udpate_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 package and php pachages
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: install php package and php packages for CentOS
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
    - name: install mariaDB package (CentOS)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install mariaDB package (CentOS)
      package:
        name: samba
        state: latest
# If "Could not reliably determine the server's fully qualified domain name"
# run this comand on remot if  apache2 not started  $ echo 'ServerName localhost   ' >>/etc/apache2/apache2.conf
#
#    - name: add ServerName to apache2
#      ansible.builtin.command:
#        cmd: echo 'ServerName localhost' >>/etc/apache2/apache2.conf

